-- up
CREATE TABLE IF NOT EXISTS products (
 id SERIAL PRIMARY KEY,
 name TEXT NOT NULL,
 price NUMERIC NOT NULL,
 discount NUMERIC NULL,
 instock BOOLEAN NOT NULL
);

-- down
DROP TABLE IF EXISTS products;
